name:                funcy-verlet
version:             0.1.0.0
github:              "rabuu/funcy-verlet"
license:             MIT
author:              "rabuu"
maintainer:          "rabuu.dev@gmail.com"
copyright:           "2022 rabuu"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/funcy-verlet#readme>

dependencies:
- base >= 4.8 && < 5
- gloss == 1.13.2.2
- gloss-rendering == 1.13.*
- Vec == 1.0.5

executables:
  funcy-verlet-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
